spring:
  application:
    name: PasswordManager
  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    session:
      timeout: 20m
      # Force the session cookie to be marked 'Secure' (Required for HTTPS browsers)
      cookie:
        secure: true
        # Use 'Lax' so the cookie is sent during the form post
        same-site: lax

  # Tell Spring to trust the 'X-Forwarded-Proto' header from your host (e.g., Render/AWS)
  forward-headers-strategy: framework
      

