spring:
  application:
    name: PasswordManager
  datasource:
    url: jdbc:postgresql://invalid-host/test
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: update

server:
  servlet:
    session:
      timeout: 20m
